### ISSUE TITLE
Plugins broken in 1.1.0

### ISSUE THREAD

**Issue by ventsislav-georgiev** [vue-formation/vue-prismjs#4]
Adding a `:plugins="['toolbar']"` on the component throws:
```
TypeError: Source: mounted hook Message: Cannot read property 'toolbar' of undefined
```
Call stack leads to:
![image](https://user-images.githubusercontent.com/5616486/37342379-0e37b3a6-26cd-11e8-934d-25227659af75.png)

**Comment by bhoriuchi** [comment]
Looks like vue didn’t like the underscore. I refactored this to check Prism for registered plugins instead. V1.2.0 published to npm
